# Site settings
title: Lametti Lab
description: Speech, Language, and Communication Lab at Acadia University
url: "https://www.lamettilab.com"
baseurl: ""

# Build settings
markdown: kramdown

# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# Navigation
navigation:
  - title: Home
    url: /
  - title: People
    url: /people/
  - title: Science
    url: /science/
  - title: Speaking
    url: /speaking/
  - title: Miscellanea
    url: /miscellanea/

# Contact
email: daniel.lametti@acadiau.ca

# Social
google_scholar: https://scholar.google.com/citations?user=Moar0_EAAAAJ&hl=en
bluesky: https://bsky.app/profile/daniellametti.com
linkedin: https://www.linkedin.com/in/daniellametti/

# Default front matter
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
